// Code generated by togo. API Resource transformer for Agent — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// AgentResponse is the JSON shape returned by the Agent API.
type AgentResponse struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Module      string    `json:"module"`
	Tagline     *string   `json:"tagline"`
	Description *string   `json:"description"`
	ImageURL    *string   `json:"image_url"`
	CtaText     string    `json:"cta_text"`
	CtaSubtext  *string   `json:"cta_subtext"`
	SortOrder   *int64    `json:"sort_order"`
	Active      bool      `json:"active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// TransformAgent maps a db row to the API response. Edit freely.
func TransformAgent(m db.Agent) AgentResponse {
	return AgentResponse{
		ID:          m.ID,
		Name:        m.Name,
		Slug:        m.Slug,
		Module:      m.Module,
		Tagline:     m.Tagline,
		Description: m.Description,
		ImageURL:    m.ImageURL,
		CtaText:     m.CtaText,
		CtaSubtext:  m.CtaSubtext,
		SortOrder:   m.SortOrder,
		Active:      m.Active,
		CreatedAt:   m.CreatedAt,
		UpdatedAt:   m.UpdatedAt,
	}
}

// TransformAgents maps a slice of db rows to API responses.
func TransformAgents(rows []db.Agent) []AgentResponse {
	out := make([]AgentResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformAgent(m)
	}
	return out
}
