// Code generated by togo. API Resource transformer for Alert — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// AlertResponse is the JSON shape returned by the Alert API.
type AlertResponse struct {
	ID           string    `json:"id"`
	Signal       string    `json:"signal"`
	Severity     string    `json:"severity"`
	Title        string    `json:"title"`
	Summary      *string   `json:"summary"`
	ArticleID    *string   `json:"article_id"`
	EntityID     *string   `json:"entity_id"`
	Acknowledged bool      `json:"acknowledged"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// TransformAlert maps a db row to the API response. Edit freely.
func TransformAlert(m db.Alert) AlertResponse {
	return AlertResponse{
		ID:           m.ID,
		Signal:       m.Signal,
		Severity:     m.Severity,
		Title:        m.Title,
		Summary:      m.Summary,
		ArticleID:    m.ArticleID,
		EntityID:     m.EntityID,
		Acknowledged: m.Acknowledged,
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
	}
}

// TransformAlerts maps a slice of db rows to API responses.
func TransformAlerts(rows []db.Alert) []AlertResponse {
	out := make([]AlertResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformAlert(m)
	}
	return out
}
