// Code generated by togo. API Resource transformer for Article — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// ArticleResponse is the JSON shape returned by the Article API.
type ArticleResponse struct {
	ID              string     `json:"id"`
	URL             string     `json:"url"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	Summary         *string    `json:"summary"`
	WhyItMatters    *string    `json:"why_it_matters"`
	SourceName      *string    `json:"source_name"`
	SourceType      string     `json:"source_type"`
	ImageURL        *string    `json:"image_url"`
	PublishedAt     *time.Time `json:"published_at"`
	Status          string     `json:"status"`
	HarvesterItemID *string    `json:"harvester_item_id"`
	LinkedVentureID *string    `json:"linked_venture_id"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

// TransformArticle maps a db row to the API response. Edit freely.
func TransformArticle(m db.Article) ArticleResponse {
	return ArticleResponse{
		ID:              m.ID,
		URL:             m.URL,
		Title:           m.Title,
		Content:         m.Content,
		Summary:         m.Summary,
		WhyItMatters:    m.WhyItMatters,
		SourceName:      m.SourceName,
		SourceType:      m.SourceType,
		ImageURL:        m.ImageURL,
		PublishedAt:     m.PublishedAt,
		Status:          m.Status,
		HarvesterItemID: m.HarvesterItemID,
		LinkedVentureID: m.LinkedVentureID,
		CreatedAt:       m.CreatedAt,
		UpdatedAt:       m.UpdatedAt,
	}
}

// TransformArticles maps a slice of db rows to API responses.
func TransformArticles(rows []db.Article) []ArticleResponse {
	out := make([]ArticleResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformArticle(m)
	}
	return out
}
