// Code generated by togo. API Resource transformer for CapabilitySource — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// CapabilitySourceResponse is the JSON shape returned by the CapabilitySource API.
type CapabilitySourceResponse struct {
	ID           string    `json:"id"`
	CapabilityID string    `json:"capability_id"`
	SourceID     string    `json:"source_id"`
	Config       string    `json:"config"`
	Active       bool      `json:"active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// TransformCapabilitySource maps a db row to the API response. Edit freely.
func TransformCapabilitySource(m db.CapabilitySource) CapabilitySourceResponse {
	return CapabilitySourceResponse{
		ID:           m.ID,
		CapabilityID: m.CapabilityID,
		SourceID:     m.SourceID,
		Config:       m.Config,
		Active:       m.Active,
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
	}
}

// TransformCapabilitySources maps a slice of db rows to API responses.
func TransformCapabilitySources(rows []db.CapabilitySource) []CapabilitySourceResponse {
	out := make([]CapabilitySourceResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformCapabilitySource(m)
	}
	return out
}
