// Code generated by togo. API Resource transformer for Capability — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// CapabilityResponse is the JSON shape returned by the Capability API.
type CapabilityResponse struct {
	ID            string    `json:"id"`
	Slug          string    `json:"slug"`
	NameEn        string    `json:"name_en"`
	NameAr        *string   `json:"name_ar"`
	Kind          string    `json:"kind"`
	Enabled       bool      `json:"enabled"`
	NavOrder      int64     `json:"nav_order"`
	NavIcon       *string   `json:"nav_icon"`
	Route         *string   `json:"route"`
	DescriptionEn *string   `json:"description_en"`
	DescriptionAr *string   `json:"description_ar"`
	Config        string    `json:"config"`
	WorkflowSteps string    `json:"workflow_steps"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// TransformCapability maps a db row to the API response. Edit freely.
func TransformCapability(m db.Capability) CapabilityResponse {
	return CapabilityResponse{
		ID:            m.ID,
		Slug:          m.Slug,
		NameEn:        m.NameEn,
		NameAr:        m.NameAr,
		Kind:          m.Kind,
		Enabled:       m.Enabled,
		NavOrder:      m.NavOrder,
		NavIcon:       m.NavIcon,
		Route:         m.Route,
		DescriptionEn: m.DescriptionEn,
		DescriptionAr: m.DescriptionAr,
		Config:        m.Config,
		WorkflowSteps: m.WorkflowSteps,
		CreatedAt:     m.CreatedAt,
		UpdatedAt:     m.UpdatedAt,
	}
}

// TransformCapabilities maps a slice of db rows to API responses.
func TransformCapabilities(rows []db.Capability) []CapabilityResponse {
	out := make([]CapabilityResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformCapability(m)
	}
	return out
}
