// Code generated by togo. API Resource transformer for Entity — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// EntityResponse is the JSON shape returned by the Entity API.
type EntityResponse struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	Kind         string    `json:"kind"`
	Description  *string   `json:"description"`
	LogoURL      *string   `json:"logo_url"`
	Website      *string   `json:"website"`
	Sector       *string   `json:"sector"`
	Headquarters *string   `json:"headquarters"`
	FoundedYear  *int64    `json:"founded_year"`
	Claimed      bool      `json:"claimed"`
	Metadata     string    `json:"metadata"` // full source record (jsonb) — all info from the directory
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// TransformEntity maps a db row to the API response. Edit freely.
func TransformEntity(m db.Entity) EntityResponse {
	return EntityResponse{
		ID:           m.ID,
		Name:         m.Name,
		Slug:         m.Slug,
		Kind:         m.Kind,
		Description:  m.Description,
		LogoURL:      m.LogoURL,
		Website:      m.Website,
		Sector:       m.Sector,
		Headquarters: m.Headquarters,
		FoundedYear:  m.FoundedYear,
		Claimed:      m.Claimed,
		Metadata:     m.Metadata,
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
	}
}

// TransformEntities maps a slice of db rows to API responses.
func TransformEntities(rows []db.Entity) []EntityResponse {
	out := make([]EntityResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformEntity(m)
	}
	return out
}
