// Code generated by togo. API Resource transformer for Lead — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// LeadResponse is the JSON shape returned by the Lead API.
type LeadResponse struct {
	ID          string    `json:"id"`
	Email       string    `json:"email"`
	Whatsapp    string    `json:"whatsapp"`
	Message     *string   `json:"message"`
	SourceType  string    `json:"source_type"`
	SourcePage  string    `json:"source_page"`
	SourceAgent *string   `json:"source_agent"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// TransformLead maps a db row to the API response. Edit freely.
func TransformLead(m db.Lead) LeadResponse {
	return LeadResponse{
		ID:          m.ID,
		Email:       m.Email,
		Whatsapp:    m.Whatsapp,
		Message:     m.Message,
		SourceType:  m.SourceType,
		SourcePage:  m.SourcePage,
		SourceAgent: m.SourceAgent,
		CreatedAt:   m.CreatedAt,
		UpdatedAt:   m.UpdatedAt,
	}
}

// TransformLeads maps a slice of db rows to API responses.
func TransformLeads(rows []db.Lead) []LeadResponse {
	out := make([]LeadResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformLead(m)
	}
	return out
}
