// Code generated by togo. API Resource transformer for Narrative — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// NarrativeResponse is the JSON shape returned by the Narrative API.
type NarrativeResponse struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Kind             string     `json:"kind"`
	BodyMd           string     `json:"body_md"`
	PeriodStart      *time.Time `json:"period_start"`
	PeriodEnd        *time.Time `json:"period_end"`
	WindowDays       *int64     `json:"window_days"`
	Model            *string    `json:"model"`
	PromptTokens     *int64     `json:"prompt_tokens"`
	CompletionTokens *int64     `json:"completion_tokens"`
	Status           string     `json:"status"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

// TransformNarrative maps a db row to the API response. Edit freely.
func TransformNarrative(m db.Narrative) NarrativeResponse {
	return NarrativeResponse{
		ID:               m.ID,
		Title:            m.Title,
		Kind:             m.Kind,
		BodyMd:           m.BodyMd,
		PeriodStart:      m.PeriodStart,
		PeriodEnd:        m.PeriodEnd,
		WindowDays:       m.WindowDays,
		Model:            m.Model,
		PromptTokens:     m.PromptTokens,
		CompletionTokens: m.CompletionTokens,
		Status:           m.Status,
		CreatedAt:        m.CreatedAt,
		UpdatedAt:        m.UpdatedAt,
	}
}

// TransformNarratives maps a slice of db rows to API responses.
func TransformNarratives(rows []db.Narrative) []NarrativeResponse {
	out := make([]NarrativeResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformNarrative(m)
	}
	return out
}
