// Code generated by togo. API Resource transformer for Prompt — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// PromptResponse is the JSON shape returned by the Prompt API.
type PromptResponse struct {
	ID           string    `json:"id"`
	CapabilityID string    `json:"capability_id"`
	PromptKey    string    `json:"prompt_key"`
	ContentEn    string    `json:"content_en"`
	ContentAr    *string   `json:"content_ar"`
	Version      int64     `json:"version"`
	Active       bool      `json:"active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// TransformPrompt maps a db row to the API response. Edit freely.
func TransformPrompt(m db.Prompt) PromptResponse {
	return PromptResponse{
		ID:           m.ID,
		CapabilityID: m.CapabilityID,
		PromptKey:    m.PromptKey,
		ContentEn:    m.ContentEn,
		ContentAr:    m.ContentAr,
		Version:      m.Version,
		Active:       m.Active,
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
	}
}

// TransformPrompts maps a slice of db rows to API responses.
func TransformPrompts(rows []db.Prompt) []PromptResponse {
	out := make([]PromptResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformPrompt(m)
	}
	return out
}
