// Code generated by togo. API Resource transformer for Source — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// SourceResponse is the JSON shape returned by the Source API.
type SourceResponse struct {
	ID        string    `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Config    string    `json:"config"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TransformSource maps a db row to the API response. Edit freely.
func TransformSource(m db.Source) SourceResponse {
	return SourceResponse{
		ID:        m.ID,
		Slug:      m.Slug,
		Name:      m.Name,
		Kind:      m.Kind,
		Config:    m.Config,
		Enabled:   m.Enabled,
		CreatedAt: m.CreatedAt,
		UpdatedAt: m.UpdatedAt,
	}
}

// TransformSources maps a slice of db rows to API responses.
func TransformSources(rows []db.Source) []SourceResponse {
	out := make([]SourceResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformSource(m)
	}
	return out
}
