// Code generated by togo. Next.js page for Leads.
"use client";

import { useLeads } from "@/lib/hooks/useLeads";

export default function LeadsPage() {
  const { data, isLoading } = useLeads();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Leads</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
