// Code generated by togo. Next.js page for Alerts.
"use client";

import { useAlerts } from "@/lib/hooks/useAlerts";

export default function AlertsPage() {
  const { data, isLoading } = useAlerts();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Alerts</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
