// Code generated by togo. Next.js page for Sources.
"use client";

import { useSources } from "@/lib/hooks/useSources";

export default function SourcesPage() {
  const { data, isLoading } = useSources();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Sources</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
