// Code generated by togo. Eloquent-style query entry for Agent.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Agents(a).Find(ctx, id)
//	models.Agents(a).Where("name", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Agents starts a query against the agents table.
func Agents(a *app.App) *orm.Query[db.Agent] {
	return orm.For[db.Agent](a.SQLDB, a.Dialect, "agents")
}
