// Code generated by togo. Eloquent-style query entry for Alert.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Alerts(a).Find(ctx, id)
//	models.Alerts(a).Where("signal", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Alerts starts a query against the alerts table.
func Alerts(a *app.App) *orm.Query[db.Alert] {
	return orm.For[db.Alert](a.SQLDB, a.Dialect, "alerts")
}
