// Code generated by togo. Eloquent-style query entry for Article.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Articles(a).Find(ctx, id)
//	models.Articles(a).Where("url", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Articles starts a query against the articles table.
func Articles(a *app.App) *orm.Query[db.Article] {
	return orm.For[db.Article](a.SQLDB, a.Dialect, "articles")
}
