// Code generated by togo. Eloquent-style query entry for CapabilitySource.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.CapabilitySources(a).Find(ctx, id)
//	models.CapabilitySources(a).Where("capability_id", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// CapabilitySources starts a query against the capability_sources table.
func CapabilitySources(a *app.App) *orm.Query[db.CapabilitySource] {
	return orm.For[db.CapabilitySource](a.SQLDB, a.Dialect, "capability_sources")
}
