// Code generated by togo. Eloquent-style query entry for Capability.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Capabilities(a).Find(ctx, id)
//	models.Capabilities(a).Where("slug", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Capabilities starts a query against the capabilities table.
func Capabilities(a *app.App) *orm.Query[db.Capability] {
	return orm.For[db.Capability](a.SQLDB, a.Dialect, "capabilities")
}
