// Code generated by togo. Eloquent-style query entry for Entity.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Entities(a).Find(ctx, id)
//	models.Entities(a).Where("name", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Entities starts a query against the entities table.
func Entities(a *app.App) *orm.Query[db.Entity] {
	return orm.For[db.Entity](a.SQLDB, a.Dialect, "entities")
}
