// Code generated by togo. Eloquent-style query entry for Lead.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Leads(a).Find(ctx, id)
//	models.Leads(a).Where("email", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Leads starts a query against the leads table.
func Leads(a *app.App) *orm.Query[db.Lead] {
	return orm.For[db.Lead](a.SQLDB, a.Dialect, "leads")
}
