// Code generated by togo. Eloquent-style query entry for Narrative.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Narratives(a).Find(ctx, id)
//	models.Narratives(a).Where("title", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Narratives starts a query against the narratives table.
func Narratives(a *app.App) *orm.Query[db.Narrative] {
	return orm.For[db.Narrative](a.SQLDB, a.Dialect, "narratives")
}
