// Code generated by togo. Eloquent-style query entry for Prompt.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Prompts(a).Find(ctx, id)
//	models.Prompts(a).Where("capability_id", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Prompts starts a query against the prompts table.
func Prompts(a *app.App) *orm.Query[db.Prompt] {
	return orm.For[db.Prompt](a.SQLDB, a.Dialect, "prompts")
}
