// Code generated by togo. Eloquent-style query entry for Source.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Sources(a).Find(ctx, id)
//	models.Sources(a).Where("slug", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
)

// Sources starts a query against the sources table.
func Sources(a *app.App) *orm.Query[db.Source] {
	return orm.For[db.Source](a.SQLDB, a.Dialect, "sources")
}
