-- Code generated by togo. SQLite query fragment - safe to edit.
-- name: GetAgent :one
SELECT * FROM agents WHERE id = ?;

-- name: ListAgents :many
SELECT * FROM agents ORDER BY created_at DESC LIMIT ? OFFSET ?;

-- name: CreateAgent :one
INSERT INTO agents (name, slug, module, tagline, description, image_url, cta_text, cta_subtext, sort_order, active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING *;

-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?;
