-- Code generated by togo. SQLite query fragment - safe to edit.
-- name: GetEntity :one
SELECT * FROM entities WHERE id = ?;

-- name: ListEntities :many
SELECT * FROM entities ORDER BY created_at DESC LIMIT ? OFFSET ?;

-- name: CreateEntity :one
INSERT INTO entities (name, slug, kind, description, logo_url, website, sector, headquarters, founded_year, claimed)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING *;

-- name: DeleteEntity :exec
DELETE FROM entities WHERE id = ?;
