-- Code generated by togo. SQLite query fragment - safe to edit.
-- name: GetLead :one
SELECT * FROM leads WHERE id = ?;

-- name: ListLeads :many
SELECT * FROM leads ORDER BY created_at DESC LIMIT ? OFFSET ?;

-- name: CreateLead :one
INSERT INTO leads (email, whatsapp, message, source_type, source_page, source_agent)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING *;

-- name: DeleteLead :exec
DELETE FROM leads WHERE id = ?;
