// Code generated by togo. REST (Huma) CRUD for agents via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterAgentRoutes mounts CRUD endpoints for agents.
// Queries use the driver-agnostic ORM; responses go through resources.TransformAgent;
// create/delete broadcast events ("agent.created"/".deleted").
func RegisterAgentRoutes(api huma.API, a *app.App) {
	huma.Register(api, huma.Operation{
		OperationID: "list-agents", Method: http.MethodGet, Path: "/api/agents",
		Summary: "List Agents", Tags: []string{"Agent"},
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.AgentResponse
	}, error) {
		rows, err := models.Agents(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.AgentResponse
		}{Body: resources.TransformAgents(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-agent", Method: http.MethodGet, Path: "/api/agents/{id}",
		Summary: "Get a Agent", Tags: []string{"Agent"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.AgentResponse
	}, error) {
		row, err := models.Agents(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("agent not found")
		}
		return &struct {
			Body resources.AgentResponse
		}{Body: resources.TransformAgent(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-agent", Method: http.MethodPost, Path: "/api/agents",
		DefaultStatus: http.StatusCreated, Summary: "Create a Agent", Tags: []string{"Agent"},
	}, func(ctx context.Context, in *struct {
		Body struct {
			Name        string  `json:"name" validate:"required"`
			Slug        string  `json:"slug" validate:"required"`
			Module      string  `json:"module" validate:"required"`
			Tagline     *string `json:"tagline"`
			Description *string `json:"description"`
			ImageURL    *string `json:"image_url"`
			CtaText     string  `json:"cta_text" validate:"required"`
			CtaSubtext  *string `json:"cta_subtext"`
			SortOrder   *int64  `json:"sort_order"`
			Active      bool    `json:"active" validate:"required"`
		}
	}) (*struct {
		Body resources.AgentResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Agents(a).Create(ctx, map[string]any{
			"name":        in.Body.Name,
			"slug":        in.Body.Slug,
			"module":      in.Body.Module,
			"tagline":     in.Body.Tagline,
			"description": in.Body.Description,
			"image_url":   in.Body.ImageURL,
			"cta_text":    in.Body.CtaText,
			"cta_subtext": in.Body.CtaSubtext,
			"sort_order":  in.Body.SortOrder,
			"active":      in.Body.Active,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "agent.created", row)
		return &struct {
			Body resources.AgentResponse
		}{Body: resources.TransformAgent(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-agent", Method: http.MethodPut, Path: "/api/agents/{id}",
		Summary: "Update a Agent", Tags: []string{"Agent"},
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Name        string  `json:"name"`
			Slug        string  `json:"slug"`
			Module      string  `json:"module"`
			Tagline     *string `json:"tagline"`
			Description *string `json:"description"`
			ImageURL    *string `json:"image_url"`
			CtaText     string  `json:"cta_text"`
			CtaSubtext  *string `json:"cta_subtext"`
			SortOrder   *int64  `json:"sort_order"`
			Active      bool    `json:"active"`
		}
	}) (*struct {
		Body resources.AgentResponse
	}, error) {
		if err := models.Agents(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"name":        in.Body.Name,
			"slug":        in.Body.Slug,
			"module":      in.Body.Module,
			"tagline":     in.Body.Tagline,
			"description": in.Body.Description,
			"image_url":   in.Body.ImageURL,
			"cta_text":    in.Body.CtaText,
			"cta_subtext": in.Body.CtaSubtext,
			"sort_order":  in.Body.SortOrder,
			"active":      in.Body.Active,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Agents(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "agent.updated", row)
		return &struct {
			Body resources.AgentResponse
		}{Body: resources.TransformAgent(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-agent", Method: http.MethodDelete, Path: "/api/agents/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Agent", Tags: []string{"Agent"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Agents(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "agent.deleted", in.ID)
		return &struct{}{}, nil
	})
}
