// Code generated by togo. REST (Huma) CRUD for alerts via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterAlertRoutes mounts CRUD endpoints for alerts.
// Queries use the driver-agnostic ORM; responses go through resources.TransformAlert;
// create/delete broadcast events ("alert.created"/".deleted").
func RegisterAlertRoutes(api huma.API, a *app.App) {
	// §1 auth boundary: list/get are PUBLIC (the intelligence feed reads alerts);
	// create/update/delete are ADMIN-ONLY.
	var adminMW huma.Middlewares
	if a != nil {
		adminMW = huma.Middlewares{NewGate(api, a.Kernel).RequireAdmin}
	}

	huma.Register(api, huma.Operation{
		OperationID: "list-alerts", Method: http.MethodGet, Path: "/api/alerts",
		Summary: "List Alerts", Tags: []string{"Alert"},
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.AlertResponse
	}, error) {
		rows, err := models.Alerts(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.AlertResponse
		}{Body: resources.TransformAlerts(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-alert", Method: http.MethodGet, Path: "/api/alerts/{id}",
		Summary: "Get a Alert", Tags: []string{"Alert"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.AlertResponse
	}, error) {
		row, err := models.Alerts(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("alert not found")
		}
		return &struct {
			Body resources.AlertResponse
		}{Body: resources.TransformAlert(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-alert", Method: http.MethodPost, Path: "/api/alerts",
		DefaultStatus: http.StatusCreated, Summary: "Create a Alert", Tags: []string{"Alert"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Body struct {
			Signal       string  `json:"signal" validate:"required"`
			Severity     string  `json:"severity" validate:"required"`
			Title        string  `json:"title" validate:"required"`
			Summary      *string `json:"summary,omitempty"`
			ArticleID    *string `json:"article_id,omitempty"`
			EntityID     *string `json:"entity_id,omitempty"`
			Acknowledged bool    `json:"acknowledged"`
		}
	}) (*struct {
		Body resources.AlertResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Alerts(a).Create(ctx, map[string]any{
			"signal":       in.Body.Signal,
			"severity":     in.Body.Severity,
			"title":        in.Body.Title,
			"summary":      in.Body.Summary,
			"article_id":   in.Body.ArticleID,
			"entity_id":    in.Body.EntityID,
			"acknowledged": in.Body.Acknowledged,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "alert.created", row)
		return &struct {
			Body resources.AlertResponse
		}{Body: resources.TransformAlert(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-alert", Method: http.MethodPut, Path: "/api/alerts/{id}",
		Summary: "Update a Alert", Tags: []string{"Alert"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Signal       string  `json:"signal"`
			Severity     string  `json:"severity"`
			Title        string  `json:"title"`
			Summary      *string `json:"summary"`
			ArticleID    *string `json:"article_id"`
			EntityID     *string `json:"entity_id"`
			Acknowledged bool    `json:"acknowledged"`
		}
	}) (*struct {
		Body resources.AlertResponse
	}, error) {
		if err := models.Alerts(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"signal":       in.Body.Signal,
			"severity":     in.Body.Severity,
			"title":        in.Body.Title,
			"summary":      in.Body.Summary,
			"article_id":   in.Body.ArticleID,
			"entity_id":    in.Body.EntityID,
			"acknowledged": in.Body.Acknowledged,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Alerts(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "alert.updated", row)
		return &struct {
			Body resources.AlertResponse
		}{Body: resources.TransformAlert(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-alert", Method: http.MethodDelete, Path: "/api/alerts/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Alert", Tags: []string{"Alert"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Alerts(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "alert.deleted", in.ID)
		return &struct{}{}, nil
	})
}
