// Code generated by togo. REST (Huma) CRUD for articles via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterArticleRoutes mounts CRUD endpoints for articles.
// Queries use the driver-agnostic ORM; responses go through resources.TransformArticle;
// create/delete broadcast events ("article.created"/".deleted").
func RegisterArticleRoutes(api huma.API, a *app.App) {
	// §1 auth boundary: list/get are PUBLIC (the /radar feed reads articles);
	// create/update/delete are ADMIN-ONLY.
	var adminMW huma.Middlewares
	if a != nil {
		adminMW = huma.Middlewares{NewGate(api, a.Kernel).RequireAdmin}
	}

	huma.Register(api, huma.Operation{
		OperationID: "list-articles", Method: http.MethodGet, Path: "/api/articles",
		Summary: "List Articles", Tags: []string{"Article"},
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.ArticleResponse
	}, error) {
		rows, err := models.Articles(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.ArticleResponse
		}{Body: resources.TransformArticles(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-article", Method: http.MethodGet, Path: "/api/articles/{id}",
		Summary: "Get a Article", Tags: []string{"Article"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.ArticleResponse
	}, error) {
		row, err := models.Articles(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("article not found")
		}
		return &struct {
			Body resources.ArticleResponse
		}{Body: resources.TransformArticle(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-article", Method: http.MethodPost, Path: "/api/articles",
		DefaultStatus: http.StatusCreated, Summary: "Create a Article", Tags: []string{"Article"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Body struct {
			URL             string     `json:"url" validate:"required"`
			Title           string     `json:"title" validate:"required"`
			Content         string     `json:"content" validate:"required"`
			Summary         *string    `json:"summary,omitempty"`
			WhyItMatters    *string    `json:"why_it_matters,omitempty"`
			SourceName      *string    `json:"source_name,omitempty"`
			SourceType      string     `json:"source_type" validate:"required"`
			ImageURL        *string    `json:"image_url,omitempty"`
			PublishedAt     *time.Time `json:"published_at,omitempty"`
			Status          string     `json:"status" validate:"required"`
			HarvesterItemID *string    `json:"harvester_item_id,omitempty"`
			LinkedVentureID *string    `json:"linked_venture_id,omitempty"`
		}
	}) (*struct {
		Body resources.ArticleResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Articles(a).Create(ctx, map[string]any{
			"url":               in.Body.URL,
			"title":             in.Body.Title,
			"content":           in.Body.Content,
			"summary":           in.Body.Summary,
			"why_it_matters":    in.Body.WhyItMatters,
			"source_name":       in.Body.SourceName,
			"source_type":       in.Body.SourceType,
			"image_url":         in.Body.ImageURL,
			"published_at":      in.Body.PublishedAt,
			"status":            in.Body.Status,
			"harvester_item_id": in.Body.HarvesterItemID,
			"linked_venture_id": in.Body.LinkedVentureID,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "article.created", row)
		return &struct {
			Body resources.ArticleResponse
		}{Body: resources.TransformArticle(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-article", Method: http.MethodPut, Path: "/api/articles/{id}",
		Summary: "Update a Article", Tags: []string{"Article"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			URL             string     `json:"url"`
			Title           string     `json:"title"`
			Content         string     `json:"content"`
			Summary         *string    `json:"summary"`
			WhyItMatters    *string    `json:"why_it_matters"`
			SourceName      *string    `json:"source_name"`
			SourceType      string     `json:"source_type"`
			ImageURL        *string    `json:"image_url"`
			PublishedAt     *time.Time `json:"published_at"`
			Status          string     `json:"status"`
			HarvesterItemID *string    `json:"harvester_item_id"`
			LinkedVentureID *string    `json:"linked_venture_id"`
		}
	}) (*struct {
		Body resources.ArticleResponse
	}, error) {
		if err := models.Articles(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"url":               in.Body.URL,
			"title":             in.Body.Title,
			"content":           in.Body.Content,
			"summary":           in.Body.Summary,
			"why_it_matters":    in.Body.WhyItMatters,
			"source_name":       in.Body.SourceName,
			"source_type":       in.Body.SourceType,
			"image_url":         in.Body.ImageURL,
			"published_at":      in.Body.PublishedAt,
			"status":            in.Body.Status,
			"harvester_item_id": in.Body.HarvesterItemID,
			"linked_venture_id": in.Body.LinkedVentureID,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Articles(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "article.updated", row)
		return &struct {
			Body resources.ArticleResponse
		}{Body: resources.TransformArticle(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-article", Method: http.MethodDelete, Path: "/api/articles/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Article", Tags: []string{"Article"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Articles(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "article.deleted", in.ID)
		return &struct{}{}, nil
	})
}
