// Code generated by togo (test) - extend with your own cases.
package rest

import (
	"context"
	"os"
	"testing"

	"github.com/danielgtaylor/huma/v2/humatest"
	"github.com/togo-framework/togo"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
)

// TestArticleAPI exercises the articles endpoints. Set
// TEST_DATABASE_URL (a migrated DB) to run it; skipped otherwise.
func TestArticleAPI(t *testing.T) {
	if os.Getenv("TEST_DATABASE_URL") == "" {
		t.Skip("set TEST_DATABASE_URL to run Article API tests")
	}
	os.Setenv("DATABASE_URL", os.Getenv("TEST_DATABASE_URL"))

	k := togo.New()
	a := app.New(context.Background(), k)
	defer k.Close()
	if a.SQLDB == nil {
		t.Skip("database unavailable")
	}

	_, api := humatest.New(t)
	RegisterArticleRoutes(api, a)

	if resp := api.Get("/api/articles"); resp.Code != 200 {
		t.Fatalf("list articles: expected 200, got %d", resp.Code)
	}
}
