// Code generated by togo. REST (Huma) CRUD for capabilities via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterCapabilityRoutes mounts CRUD endpoints for capabilities.
// Queries use the driver-agnostic ORM; responses go through resources.TransformCapability;
// create/delete broadcast events ("capability.created"/".deleted").
func RegisterCapabilityRoutes(api huma.API, a *app.App) {
	// §1 auth boundary: list/get are PUBLIC (the site reads enabled capabilities);
	// create/update/delete are ADMIN-ONLY.
	var adminMW huma.Middlewares
	if a != nil {
		adminMW = huma.Middlewares{NewGate(api, a.Kernel).RequireAdmin}
	}

	huma.Register(api, huma.Operation{
		OperationID: "list-capabilities", Method: http.MethodGet, Path: "/api/capabilities",
		Summary: "List Capabilities", Tags: []string{"Capability"},
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.CapabilityResponse
	}, error) {
		rows, err := models.Capabilities(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.CapabilityResponse
		}{Body: resources.TransformCapabilities(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-capability", Method: http.MethodGet, Path: "/api/capabilities/{id}",
		Summary: "Get a Capability", Tags: []string{"Capability"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.CapabilityResponse
	}, error) {
		row, err := models.Capabilities(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("capability not found")
		}
		return &struct {
			Body resources.CapabilityResponse
		}{Body: resources.TransformCapability(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-capability", Method: http.MethodPost, Path: "/api/capabilities",
		DefaultStatus: http.StatusCreated, Summary: "Create a Capability", Tags: []string{"Capability"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Body struct {
			Slug          string  `json:"slug" validate:"required"`
			NameEn        string  `json:"name_en" validate:"required"`
			NameAr        *string `json:"name_ar,omitempty"`
			Kind          string  `json:"kind" validate:"required"`
			Enabled       bool    `json:"enabled" validate:"required"`
			NavOrder      int64   `json:"nav_order" validate:"required"`
			NavIcon       *string `json:"nav_icon,omitempty"`
			Route         *string `json:"route,omitempty"`
			DescriptionEn *string `json:"description_en,omitempty"`
			DescriptionAr *string `json:"description_ar,omitempty"`
			Config        string  `json:"config" validate:"required"`
			WorkflowSteps string  `json:"workflow_steps" validate:"required"`
		}
	}) (*struct {
		Body resources.CapabilityResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Capabilities(a).Create(ctx, map[string]any{
			"slug":           in.Body.Slug,
			"name_en":        in.Body.NameEn,
			"name_ar":        in.Body.NameAr,
			"kind":           in.Body.Kind,
			"enabled":        in.Body.Enabled,
			"nav_order":      in.Body.NavOrder,
			"nav_icon":       in.Body.NavIcon,
			"route":          in.Body.Route,
			"description_en": in.Body.DescriptionEn,
			"description_ar": in.Body.DescriptionAr,
			"config":         in.Body.Config,
			"workflow_steps": in.Body.WorkflowSteps,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "capability.created", row)
		return &struct {
			Body resources.CapabilityResponse
		}{Body: resources.TransformCapability(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-capability", Method: http.MethodPut, Path: "/api/capabilities/{id}",
		Summary: "Update a Capability", Tags: []string{"Capability"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Slug          string  `json:"slug"`
			NameEn        string  `json:"name_en"`
			NameAr        *string `json:"name_ar,omitempty"`
			Kind          string  `json:"kind"`
			Enabled       bool    `json:"enabled"`
			NavOrder      int64   `json:"nav_order"`
			NavIcon       *string `json:"nav_icon,omitempty"`
			Route         *string `json:"route,omitempty"`
			DescriptionEn *string `json:"description_en,omitempty"`
			DescriptionAr *string `json:"description_ar,omitempty"`
			Config        string  `json:"config"`
			WorkflowSteps string  `json:"workflow_steps"`
		}
	}) (*struct {
		Body resources.CapabilityResponse
	}, error) {
		if err := models.Capabilities(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"slug":           in.Body.Slug,
			"name_en":        in.Body.NameEn,
			"name_ar":        in.Body.NameAr,
			"kind":           in.Body.Kind,
			"enabled":        in.Body.Enabled,
			"nav_order":      in.Body.NavOrder,
			"nav_icon":       in.Body.NavIcon,
			"route":          in.Body.Route,
			"description_en": in.Body.DescriptionEn,
			"description_ar": in.Body.DescriptionAr,
			"config":         in.Body.Config,
			"workflow_steps": in.Body.WorkflowSteps,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Capabilities(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "capability.updated", row)
		return &struct {
			Body resources.CapabilityResponse
		}{Body: resources.TransformCapability(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-capability", Method: http.MethodDelete, Path: "/api/capabilities/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Capability", Tags: []string{"Capability"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Capabilities(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "capability.deleted", in.ID)
		return &struct{}{}, nil
	})
}
