// Code generated by togo. REST (Huma) CRUD for capability_sources via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterCapabilitySourceRoutes mounts CRUD endpoints for capability_sources.
// Queries use the driver-agnostic ORM; responses go through resources.TransformCapabilitySource;
// create/delete broadcast events ("capability_source.created"/".deleted").
func RegisterCapabilitySourceRoutes(api huma.API, a *app.App) {
	// §1 auth boundary: capability_sources hold internal config, so ALL operations
	// are ADMIN-ONLY.
	var adminMW huma.Middlewares
	if a != nil {
		adminMW = huma.Middlewares{NewGate(api, a.Kernel).RequireAdmin}
	}

	huma.Register(api, huma.Operation{
		OperationID: "list-capability-sources", Method: http.MethodGet, Path: "/api/capability_sources",
		Summary: "List CapabilitySources", Tags: []string{"CapabilitySource"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.CapabilitySourceResponse
	}, error) {
		rows, err := models.CapabilitySources(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.CapabilitySourceResponse
		}{Body: resources.TransformCapabilitySources(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-capability-source", Method: http.MethodGet, Path: "/api/capability_sources/{id}",
		Summary: "Get a CapabilitySource", Tags: []string{"CapabilitySource"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.CapabilitySourceResponse
	}, error) {
		row, err := models.CapabilitySources(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("capabilitysource not found")
		}
		return &struct {
			Body resources.CapabilitySourceResponse
		}{Body: resources.TransformCapabilitySource(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-capability-source", Method: http.MethodPost, Path: "/api/capability_sources",
		DefaultStatus: http.StatusCreated, Summary: "Create a CapabilitySource", Tags: []string{"CapabilitySource"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Body struct {
			CapabilityID string `json:"capability_id" validate:"required"`
			SourceID     string `json:"source_id" validate:"required"`
			Config       string `json:"config" validate:"required"`
			Active       bool   `json:"active" validate:"required"`
		}
	}) (*struct {
		Body resources.CapabilitySourceResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.CapabilitySources(a).Create(ctx, map[string]any{
			"capability_id": in.Body.CapabilityID,
			"source_id":     in.Body.SourceID,
			"config":        in.Body.Config,
			"active":        in.Body.Active,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "capability_source.created", row)
		return &struct {
			Body resources.CapabilitySourceResponse
		}{Body: resources.TransformCapabilitySource(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-capability-source", Method: http.MethodPut, Path: "/api/capability_sources/{id}",
		Summary: "Update a CapabilitySource", Tags: []string{"CapabilitySource"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			CapabilityID string `json:"capability_id"`
			SourceID     string `json:"source_id"`
			Config       string `json:"config"`
			Active       bool   `json:"active"`
		}
	}) (*struct {
		Body resources.CapabilitySourceResponse
	}, error) {
		if err := models.CapabilitySources(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"capability_id": in.Body.CapabilityID,
			"source_id":     in.Body.SourceID,
			"config":        in.Body.Config,
			"active":        in.Body.Active,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.CapabilitySources(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "capability_source.updated", row)
		return &struct {
			Body resources.CapabilitySourceResponse
		}{Body: resources.TransformCapabilitySource(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-capability-source", Method: http.MethodDelete, Path: "/api/capability_sources/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a CapabilitySource", Tags: []string{"CapabilitySource"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.CapabilitySources(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "capability_source.deleted", in.ID)
		return &struct{}{}, nil
	})
}
