// Code generated by togo. REST (Huma) CRUD for entities via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterEntityRoutes mounts CRUD endpoints for entities.
// Queries use the driver-agnostic ORM; responses go through resources.TransformEntity;
// create/delete broadcast events ("entity.created"/".deleted").
func RegisterEntityRoutes(api huma.API, a *app.App) {
	huma.Register(api, huma.Operation{
		OperationID: "list-entities", Method: http.MethodGet, Path: "/api/entities",
		Summary: "List Entities", Tags: []string{"Entity"},
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.EntityResponse
	}, error) {
		rows, err := models.Entities(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.EntityResponse
		}{Body: resources.TransformEntities(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-entity", Method: http.MethodGet, Path: "/api/entities/{id}",
		Summary: "Get a Entity", Tags: []string{"Entity"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.EntityResponse
	}, error) {
		row, err := models.Entities(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("entity not found")
		}
		return &struct {
			Body resources.EntityResponse
		}{Body: resources.TransformEntity(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-entity", Method: http.MethodPost, Path: "/api/entities",
		DefaultStatus: http.StatusCreated, Summary: "Create a Entity", Tags: []string{"Entity"},
	}, func(ctx context.Context, in *struct {
		Body struct {
			Name         string  `json:"name" validate:"required"`
			Slug         string  `json:"slug" validate:"required"`
			Kind         string  `json:"kind" validate:"required"`
			Description  *string `json:"description"`
			LogoURL      *string `json:"logo_url"`
			Website      *string `json:"website"`
			Sector       *string `json:"sector"`
			Headquarters *string `json:"headquarters"`
			FoundedYear  *int64  `json:"founded_year"`
			Claimed      bool    `json:"claimed" validate:"required"`
		}
	}) (*struct {
		Body resources.EntityResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Entities(a).Create(ctx, map[string]any{
			"name":         in.Body.Name,
			"slug":         in.Body.Slug,
			"kind":         in.Body.Kind,
			"description":  in.Body.Description,
			"logo_url":     in.Body.LogoURL,
			"website":      in.Body.Website,
			"sector":       in.Body.Sector,
			"headquarters": in.Body.Headquarters,
			"founded_year": in.Body.FoundedYear,
			"claimed":      in.Body.Claimed,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "entity.created", row)
		return &struct {
			Body resources.EntityResponse
		}{Body: resources.TransformEntity(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-entity", Method: http.MethodPut, Path: "/api/entities/{id}",
		Summary: "Update a Entity", Tags: []string{"Entity"},
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Name         string  `json:"name"`
			Slug         string  `json:"slug"`
			Kind         string  `json:"kind"`
			Description  *string `json:"description"`
			LogoURL      *string `json:"logo_url"`
			Website      *string `json:"website"`
			Sector       *string `json:"sector"`
			Headquarters *string `json:"headquarters"`
			FoundedYear  *int64  `json:"founded_year"`
			Claimed      bool    `json:"claimed"`
		}
	}) (*struct {
		Body resources.EntityResponse
	}, error) {
		if err := models.Entities(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"name":         in.Body.Name,
			"slug":         in.Body.Slug,
			"kind":         in.Body.Kind,
			"description":  in.Body.Description,
			"logo_url":     in.Body.LogoURL,
			"website":      in.Body.Website,
			"sector":       in.Body.Sector,
			"headquarters": in.Body.Headquarters,
			"founded_year": in.Body.FoundedYear,
			"claimed":      in.Body.Claimed,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Entities(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "entity.updated", row)
		return &struct {
			Body resources.EntityResponse
		}{Body: resources.TransformEntity(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-entity", Method: http.MethodDelete, Path: "/api/entities/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Entity", Tags: []string{"Entity"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Entities(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "entity.deleted", in.ID)
		return &struct{}{}, nil
	})
}
