// Code generated by togo. REST (Huma) CRUD for leads via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterLeadRoutes mounts CRUD endpoints for leads.
// Queries use the driver-agnostic ORM; responses go through resources.TransformLead;
// create/delete broadcast events ("lead.created"/".deleted").
func RegisterLeadRoutes(api huma.API, a *app.App) {
	huma.Register(api, huma.Operation{
		OperationID: "list-leads", Method: http.MethodGet, Path: "/api/leads",
		Summary: "List Leads", Tags: []string{"Lead"},
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.LeadResponse
	}, error) {
		rows, err := models.Leads(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.LeadResponse
		}{Body: resources.TransformLeads(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-lead", Method: http.MethodGet, Path: "/api/leads/{id}",
		Summary: "Get a Lead", Tags: []string{"Lead"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.LeadResponse
	}, error) {
		row, err := models.Leads(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("lead not found")
		}
		return &struct {
			Body resources.LeadResponse
		}{Body: resources.TransformLead(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-lead", Method: http.MethodPost, Path: "/api/leads",
		DefaultStatus: http.StatusCreated, Summary: "Create a Lead", Tags: []string{"Lead"},
	}, func(ctx context.Context, in *struct {
		Body struct {
			Email       string  `json:"email" validate:"required"`
			Whatsapp    string  `json:"whatsapp" validate:"required"`
			Message     *string `json:"message"`
			SourceType  string  `json:"source_type" validate:"required"`
			SourcePage  string  `json:"source_page" validate:"required"`
			SourceAgent *string `json:"source_agent"`
		}
	}) (*struct {
		Body resources.LeadResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Leads(a).Create(ctx, map[string]any{
			"email":        in.Body.Email,
			"whatsapp":     in.Body.Whatsapp,
			"message":      in.Body.Message,
			"source_type":  in.Body.SourceType,
			"source_page":  in.Body.SourcePage,
			"source_agent": in.Body.SourceAgent,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "lead.created", row)
		return &struct {
			Body resources.LeadResponse
		}{Body: resources.TransformLead(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-lead", Method: http.MethodPut, Path: "/api/leads/{id}",
		Summary: "Update a Lead", Tags: []string{"Lead"},
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Email       string  `json:"email"`
			Whatsapp    string  `json:"whatsapp"`
			Message     *string `json:"message"`
			SourceType  string  `json:"source_type"`
			SourcePage  string  `json:"source_page"`
			SourceAgent *string `json:"source_agent"`
		}
	}) (*struct {
		Body resources.LeadResponse
	}, error) {
		if err := models.Leads(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"email":        in.Body.Email,
			"whatsapp":     in.Body.Whatsapp,
			"message":      in.Body.Message,
			"source_type":  in.Body.SourceType,
			"source_page":  in.Body.SourcePage,
			"source_agent": in.Body.SourceAgent,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Leads(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "lead.updated", row)
		return &struct {
			Body resources.LeadResponse
		}{Body: resources.TransformLead(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-lead", Method: http.MethodDelete, Path: "/api/leads/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Lead", Tags: []string{"Lead"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Leads(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "lead.deleted", in.ID)
		return &struct{}{}, nil
	})
}
