// Code generated by togo. REST (Huma) CRUD for narratives via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterNarrativeRoutes mounts CRUD endpoints for narratives.
// Queries use the driver-agnostic ORM; responses go through resources.TransformNarrative;
// create/delete broadcast events ("narrative.created"/".deleted").
func RegisterNarrativeRoutes(api huma.API, a *app.App) {
	// §1 auth boundary: list/get are PUBLIC (the intelligence feed reads narratives);
	// create/update/delete are ADMIN-ONLY.
	var adminMW huma.Middlewares
	if a != nil {
		adminMW = huma.Middlewares{NewGate(api, a.Kernel).RequireAdmin}
	}

	huma.Register(api, huma.Operation{
		OperationID: "list-narratives", Method: http.MethodGet, Path: "/api/narratives",
		Summary: "List Narratives", Tags: []string{"Narrative"},
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.NarrativeResponse
	}, error) {
		rows, err := models.Narratives(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.NarrativeResponse
		}{Body: resources.TransformNarratives(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-narrative", Method: http.MethodGet, Path: "/api/narratives/{id}",
		Summary: "Get a Narrative", Tags: []string{"Narrative"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.NarrativeResponse
	}, error) {
		row, err := models.Narratives(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("narrative not found")
		}
		return &struct {
			Body resources.NarrativeResponse
		}{Body: resources.TransformNarrative(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-narrative", Method: http.MethodPost, Path: "/api/narratives",
		DefaultStatus: http.StatusCreated, Summary: "Create a Narrative", Tags: []string{"Narrative"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Body struct {
			Title            string     `json:"title" validate:"required"`
			Kind             string     `json:"kind" validate:"required"`
			BodyMd           string     `json:"body_md" validate:"required"`
			PeriodStart      *time.Time `json:"period_start,omitempty"`
			PeriodEnd        *time.Time `json:"period_end,omitempty"`
			WindowDays       *int64     `json:"window_days,omitempty"`
			Model            *string    `json:"model,omitempty"`
			PromptTokens     *int64     `json:"prompt_tokens,omitempty"`
			CompletionTokens *int64     `json:"completion_tokens,omitempty"`
			Status           string     `json:"status" validate:"required"`
		}
	}) (*struct {
		Body resources.NarrativeResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Narratives(a).Create(ctx, map[string]any{
			"title":             in.Body.Title,
			"kind":              in.Body.Kind,
			"body_md":           in.Body.BodyMd,
			"period_start":      in.Body.PeriodStart,
			"period_end":        in.Body.PeriodEnd,
			"window_days":       in.Body.WindowDays,
			"model":             in.Body.Model,
			"prompt_tokens":     in.Body.PromptTokens,
			"completion_tokens": in.Body.CompletionTokens,
			"status":            in.Body.Status,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "narrative.created", row)
		return &struct {
			Body resources.NarrativeResponse
		}{Body: resources.TransformNarrative(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-narrative", Method: http.MethodPut, Path: "/api/narratives/{id}",
		Summary: "Update a Narrative", Tags: []string{"Narrative"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Title            string     `json:"title"`
			Kind             string     `json:"kind"`
			BodyMd           string     `json:"body_md"`
			PeriodStart      *time.Time `json:"period_start"`
			PeriodEnd        *time.Time `json:"period_end"`
			WindowDays       *int64     `json:"window_days"`
			Model            *string    `json:"model"`
			PromptTokens     *int64     `json:"prompt_tokens"`
			CompletionTokens *int64     `json:"completion_tokens"`
			Status           string     `json:"status"`
		}
	}) (*struct {
		Body resources.NarrativeResponse
	}, error) {
		if err := models.Narratives(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"title":             in.Body.Title,
			"kind":              in.Body.Kind,
			"body_md":           in.Body.BodyMd,
			"period_start":      in.Body.PeriodStart,
			"period_end":        in.Body.PeriodEnd,
			"window_days":       in.Body.WindowDays,
			"model":             in.Body.Model,
			"prompt_tokens":     in.Body.PromptTokens,
			"completion_tokens": in.Body.CompletionTokens,
			"status":            in.Body.Status,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Narratives(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "narrative.updated", row)
		return &struct {
			Body resources.NarrativeResponse
		}{Body: resources.TransformNarrative(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-narrative", Method: http.MethodDelete, Path: "/api/narratives/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Narrative", Tags: []string{"Narrative"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Narratives(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "narrative.deleted", in.ID)
		return &struct{}{}, nil
	})
}
