// Code generated by togo. REST (Huma) CRUD for prompts via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterPromptRoutes mounts CRUD endpoints for prompts.
// Queries use the driver-agnostic ORM; responses go through resources.TransformPrompt;
// create/delete broadcast events ("prompt.created"/".deleted").
func RegisterPromptRoutes(api huma.API, a *app.App) {
	// §1 auth boundary: prompts are internal config, so ALL operations are
	// ADMIN-ONLY.
	var adminMW huma.Middlewares
	if a != nil {
		adminMW = huma.Middlewares{NewGate(api, a.Kernel).RequireAdmin}
	}

	huma.Register(api, huma.Operation{
		OperationID: "list-prompts", Method: http.MethodGet, Path: "/api/prompts",
		Summary: "List Prompts", Tags: []string{"Prompt"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.PromptResponse
	}, error) {
		rows, err := models.Prompts(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.PromptResponse
		}{Body: resources.TransformPrompts(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-prompt", Method: http.MethodGet, Path: "/api/prompts/{id}",
		Summary: "Get a Prompt", Tags: []string{"Prompt"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.PromptResponse
	}, error) {
		row, err := models.Prompts(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("prompt not found")
		}
		return &struct {
			Body resources.PromptResponse
		}{Body: resources.TransformPrompt(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-prompt", Method: http.MethodPost, Path: "/api/prompts",
		DefaultStatus: http.StatusCreated, Summary: "Create a Prompt", Tags: []string{"Prompt"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Body struct {
			CapabilityID string  `json:"capability_id" validate:"required"`
			PromptKey    string  `json:"prompt_key" validate:"required"`
			ContentEn    string  `json:"content_en" validate:"required"`
			ContentAr    *string `json:"content_ar,omitempty"`
			Version      int64   `json:"version" validate:"required"`
			Active       bool    `json:"active" validate:"required"`
		}
	}) (*struct {
		Body resources.PromptResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Prompts(a).Create(ctx, map[string]any{
			"capability_id": in.Body.CapabilityID,
			"prompt_key":    in.Body.PromptKey,
			"content_en":    in.Body.ContentEn,
			"content_ar":    in.Body.ContentAr,
			"version":       in.Body.Version,
			"active":        in.Body.Active,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "prompt.created", row)
		return &struct {
			Body resources.PromptResponse
		}{Body: resources.TransformPrompt(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-prompt", Method: http.MethodPut, Path: "/api/prompts/{id}",
		Summary: "Update a Prompt", Tags: []string{"Prompt"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			CapabilityID string  `json:"capability_id"`
			PromptKey    string  `json:"prompt_key"`
			ContentEn    string  `json:"content_en"`
			ContentAr    *string `json:"content_ar,omitempty"`
			Version      int64   `json:"version"`
			Active       bool    `json:"active"`
		}
	}) (*struct {
		Body resources.PromptResponse
	}, error) {
		if err := models.Prompts(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"capability_id": in.Body.CapabilityID,
			"prompt_key":    in.Body.PromptKey,
			"content_en":    in.Body.ContentEn,
			"content_ar":    in.Body.ContentAr,
			"version":       in.Body.Version,
			"active":        in.Body.Active,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Prompts(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "prompt.updated", row)
		return &struct {
			Body resources.PromptResponse
		}{Body: resources.TransformPrompt(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-prompt", Method: http.MethodDelete, Path: "/api/prompts/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Prompt", Tags: []string{"Prompt"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Prompts(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "prompt.deleted", in.ID)
		return &struct{}{}, nil
	})
}
