// Code generated by togo. REST (Huma) CRUD for sources via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
	"github.com/saudi-ventures/saudi-ventures/internal/resources"
)

// RegisterSourceRoutes mounts CRUD endpoints for sources.
// Queries use the driver-agnostic ORM; responses go through resources.TransformSource;
// create/delete broadcast events ("source.created"/".deleted").
func RegisterSourceRoutes(api huma.API, a *app.App) {
	// §1 auth boundary: sources hold internal config (may carry credentials), so
	// ALL operations are ADMIN-ONLY.
	var adminMW huma.Middlewares
	if a != nil {
		adminMW = huma.Middlewares{NewGate(api, a.Kernel).RequireAdmin}
	}

	huma.Register(api, huma.Operation{
		OperationID: "list-sources", Method: http.MethodGet, Path: "/api/sources",
		Summary: "List Sources", Tags: []string{"Source"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.SourceResponse
	}, error) {
		rows, err := models.Sources(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.SourceResponse
		}{Body: resources.TransformSources(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-source", Method: http.MethodGet, Path: "/api/sources/{id}",
		Summary: "Get a Source", Tags: []string{"Source"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.SourceResponse
	}, error) {
		row, err := models.Sources(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("source not found")
		}
		return &struct {
			Body resources.SourceResponse
		}{Body: resources.TransformSource(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-source", Method: http.MethodPost, Path: "/api/sources",
		DefaultStatus: http.StatusCreated, Summary: "Create a Source", Tags: []string{"Source"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		Body struct {
			Slug    string `json:"slug" validate:"required"`
			Name    string `json:"name" validate:"required"`
			Kind    string `json:"kind" validate:"required"`
			Config  string `json:"config" validate:"required"`
			Enabled bool   `json:"enabled" validate:"required"`
		}
	}) (*struct {
		Body resources.SourceResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Sources(a).Create(ctx, map[string]any{
			"slug":    in.Body.Slug,
			"name":    in.Body.Name,
			"kind":    in.Body.Kind,
			"config":  in.Body.Config,
			"enabled": in.Body.Enabled,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "source.created", row)
		return &struct {
			Body resources.SourceResponse
		}{Body: resources.TransformSource(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-source", Method: http.MethodPut, Path: "/api/sources/{id}",
		Summary: "Update a Source", Tags: []string{"Source"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Slug    string `json:"slug"`
			Name    string `json:"name"`
			Kind    string `json:"kind"`
			Config  string `json:"config"`
			Enabled bool   `json:"enabled"`
		}
	}) (*struct {
		Body resources.SourceResponse
	}, error) {
		if err := models.Sources(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"slug":    in.Body.Slug,
			"name":    in.Body.Name,
			"kind":    in.Body.Kind,
			"config":  in.Body.Config,
			"enabled": in.Body.Enabled,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Sources(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "source.updated", row)
		return &struct {
			Body resources.SourceResponse
		}{Body: resources.TransformSource(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-source", Method: http.MethodDelete, Path: "/api/sources/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Source", Tags: []string{"Source"}, Middlewares: adminMW,
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Sources(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "source.deleted", in.ID)
		return &struct{}{}, nil
	})
}
