// Code generated by togo. API type for Agent.
export interface Agent {
  id: string;
  name: string;
  slug: string;
  module: string;
  tagline?: string;
  description?: string;
  imageURL?: string;
  ctaText: string;
  ctaSubtext?: string;
  sortOrder?: number;
  active: boolean;
  created_at: string;
  updated_at: string;
}
