// Code generated by togo. API type for Alert.
export interface Alert {
  id: string;
  signal: string;
  severity: string;
  title: string;
  summary?: string;
  articleID?: string;
  entityID?: string;
  acknowledged: boolean;
  created_at: string;
  updated_at: string;
}
