// Code generated by togo. API type for Article.
export interface Article {
  id: string;
  uRL: string;
  title: string;
  content: string;
  summary?: string;
  whyItMatters?: string;
  sourceName?: string;
  sourceType: string;
  imageURL?: string;
  publishedAt?: string;
  status: string;
  harvesterItemID?: string;
  linkedVentureID?: string;
  created_at: string;
  updated_at: string;
}
