// Code generated by togo. API type for Capability.
export interface Capability {
  id: string;
  slug: string;
  nameEn: string;
  nameAr?: string;
  kind: string;
  enabled: boolean;
  navOrder: number;
  navIcon?: string;
  route?: string;
  descriptionEn?: string;
  descriptionAr?: string;
  config: string;
  workflowSteps: string;
  created_at: string;
  updated_at: string;
}
