// Code generated by togo. API type for CapabilitySource.
export interface CapabilitySource {
  id: string;
  capabilityID: string;
  sourceID: string;
  config: string;
  active: boolean;
  created_at: string;
  updated_at: string;
}
