// Code generated by togo. API type for Entity.
export interface Entity {
  id: string;
  name: string;
  slug: string;
  kind: string;
  description?: string;
  logoURL?: string;
  website?: string;
  sector?: string;
  headquarters?: string;
  foundedYear?: number;
  claimed: boolean;
  created_at: string;
  updated_at: string;
}
