// Code generated by togo. API type for Lead.
export interface Lead {
  id: string;
  email: string;
  whatsapp: string;
  message?: string;
  sourceType: string;
  sourcePage: string;
  sourceAgent?: string;
  created_at: string;
  updated_at: string;
}
