// Code generated by togo. API type for Narrative.
export interface Narrative {
  id: string;
  title: string;
  kind: string;
  bodyMd: string;
  periodStart?: string;
  periodEnd?: string;
  windowDays?: number;
  model?: string;
  promptTokens?: number;
  completionTokens?: number;
  status: string;
  created_at: string;
  updated_at: string;
}
