// Code generated by togo. API type for Prompt.
export interface Prompt {
  id: string;
  capabilityID: string;
  promptKey: string;
  contentEn: string;
  contentAr?: string;
  version: number;
  active: boolean;
  created_at: string;
  updated_at: string;
}
