// Code generated by togo. API type for Source.
export interface Source {
  id: string;
  slug: string;
  name: string;
  kind: string;
  config: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}
