// Code generated by togo. Next.js page for Capabilities.
"use client";

import { useCapabilities } from "@/lib/hooks/useCapabilities";

export default function CapabilitiesPage() {
  const { data, isLoading } = useCapabilities();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Capabilities</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
