// Code generated by togo. Data hook for Articles.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Article } from "@/lib/api/article";

export function useArticles() {
  return useSWR<Article[]>("/articles", apiFetch);
}
