// Code generated by togo. Data hook for Agents.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Agent } from "@/lib/api/agent";

export function useAgents() {
  return useSWR<Agent[]>("/agents", apiFetch);
}
