// Code generated by togo. Data hook for Alerts.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Alert } from "@/lib/api/alert";

export function useAlerts() {
  return useSWR<Alert[]>("/alerts", apiFetch);
}
