// Code generated by togo. Data hook for Capabilities.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Capability } from "@/lib/api/capability";

export function useCapabilities() {
  return useSWR<Capability[]>("/capabilities", apiFetch);
}
