// Code generated by togo. Data hook for CapabilitySources.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { CapabilitySource } from "@/lib/api/capability_source";

export function useCapabilitySources() {
  return useSWR<CapabilitySource[]>("/capability_sources", apiFetch);
}
