// Code generated by togo. Data hook for Entities.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Entity } from "@/lib/api/entity";

export function useEntities() {
  return useSWR<Entity[]>("/entities", apiFetch);
}
