// Code generated by togo. Data hook for Leads.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Lead } from "@/lib/api/lead";

export function useLeads() {
  return useSWR<Lead[]>("/leads", apiFetch);
}
