// Code generated by togo. Data hook for Narratives.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Narrative } from "@/lib/api/narrative";

export function useNarratives() {
  return useSWR<Narrative[]>("/narratives", apiFetch);
}
