// Code generated by togo. Data hook for Prompts.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Prompt } from "@/lib/api/prompt";

export function usePrompts() {
  return useSWR<Prompt[]>("/prompts", apiFetch);
}
