// Code generated by togo. Data hook for Sources.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Source } from "@/lib/api/source";

export function useSources() {
  return useSWR<Source[]>("/sources", apiFetch);
}
