// Code generated by togo. Next.js page for CapabilitySources.
"use client";

import { useCapabilitySources } from "@/lib/hooks/useCapabilitySources";

export default function CapabilitySourcesPage() {
  const { data, isLoading } = useCapabilitySources();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">CapabilitySources</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
