// Code generated by togo. Next.js page for Entities.
"use client";

import { useEntities } from "@/lib/hooks/useEntities";

export default function EntitiesPage() {
  const { data, isLoading } = useEntities();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Entities</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
