// Code generated by togo. Next.js page for Agents.
"use client";

import { useAgents } from "@/lib/hooks/useAgents";

export default function AgentsPage() {
  const { data, isLoading } = useAgents();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Agents</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
