// Code generated by togo. Factory — builds fake Agents via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// AgentFactory builds fake Agent records.
type AgentFactory struct {
	app   *app.App
	count int
}

// Agents starts a factory for Agents.
func Agents(a *app.App) *AgentFactory {
	return &AgentFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *AgentFactory) Count(n int) *AgentFactory { f.count = n; return f }

// Definition returns fake attributes for one Agent. Edit to taste.
func (f *AgentFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"name":        faker.Name(),
		"slug":        faker.Words(3),
		"module":      faker.Words(3),
		"tagline":     faker.Words(3),
		"description": faker.Paragraph(),
		"image_url":   "https://" + faker.Word() + ".example.com",
		"cta_text":    faker.Words(3),
		"cta_subtext": faker.Words(3),
		"sort_order":  faker.Int(1, 1000),
		"active":      faker.Bool(),
	}
}

// Create builds and persists Count records via the ORM.
func (f *AgentFactory) Create(ctx context.Context) ([]db.Agent, error) {
	out := make([]db.Agent, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Agents(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
