// Code generated by togo. Factory — builds fake Alerts via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// AlertFactory builds fake Alert records.
type AlertFactory struct {
	app   *app.App
	count int
}

// Alerts starts a factory for Alerts.
func Alerts(a *app.App) *AlertFactory {
	return &AlertFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *AlertFactory) Count(n int) *AlertFactory { f.count = n; return f }

// Definition returns fake attributes for one Alert. Edit to taste.
func (f *AlertFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"signal":       faker.Words(3),
		"severity":     faker.Words(3),
		"title":        faker.Name(),
		"summary":      faker.Words(3),
		"article_id":   faker.Words(3),
		"entity_id":    faker.Words(3),
		"acknowledged": faker.Bool(),
	}
}

// Create builds and persists Count records via the ORM.
func (f *AlertFactory) Create(ctx context.Context) ([]db.Alert, error) {
	out := make([]db.Alert, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Alerts(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
