// Code generated by togo. Factory — builds fake Articles via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// ArticleFactory builds fake Article records.
type ArticleFactory struct {
	app   *app.App
	count int
}

// Articles starts a factory for Articles.
func Articles(a *app.App) *ArticleFactory {
	return &ArticleFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *ArticleFactory) Count(n int) *ArticleFactory { f.count = n; return f }

// Definition returns fake attributes for one Article. Edit to taste.
func (f *ArticleFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"url":               "https://" + faker.Word() + ".example.com",
		"title":             faker.Name(),
		"content":           faker.Paragraph(),
		"summary":           faker.Words(3),
		"why_it_matters":    faker.Words(3),
		"source_name":       faker.Name(),
		"source_type":       faker.Words(3),
		"image_url":         "https://" + faker.Word() + ".example.com",
		"published_at":      faker.Time(),
		"status":            faker.Words(3),
		"harvester_item_id": faker.Words(3),
		"linked_venture_id": "https://" + faker.Word() + ".example.com",
	}
}

// Create builds and persists Count records via the ORM.
func (f *ArticleFactory) Create(ctx context.Context) ([]db.Article, error) {
	out := make([]db.Article, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Articles(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
