// Code generated by togo. Factory — builds fake Capabilities via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// CapabilityFactory builds fake Capability records.
type CapabilityFactory struct {
	app   *app.App
	count int
}

// Capabilities starts a factory for Capabilities.
func Capabilities(a *app.App) *CapabilityFactory {
	return &CapabilityFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *CapabilityFactory) Count(n int) *CapabilityFactory { f.count = n; return f }

// Definition returns fake attributes for one Capability. Edit to taste.
func (f *CapabilityFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"slug":           faker.Words(3),
		"name_en":        faker.Words(3),
		"name_ar":        faker.Words(3),
		"kind":           faker.Words(3),
		"enabled":        faker.Bool(),
		"nav_order":      faker.Int(1, 1000),
		"nav_icon":       faker.Words(3),
		"route":          faker.Words(3),
		"description_en": faker.Paragraph(),
		"description_ar": faker.Paragraph(),
		"config":         faker.Words(3),
		"workflow_steps": faker.Words(3),
	}
}

// Create builds and persists Count records via the ORM.
func (f *CapabilityFactory) Create(ctx context.Context) ([]db.Capability, error) {
	out := make([]db.Capability, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Capabilities(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
