// Code generated by togo. Factory — builds fake CapabilitySources via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// CapabilitySourceFactory builds fake CapabilitySource records.
type CapabilitySourceFactory struct {
	app   *app.App
	count int
}

// CapabilitySources starts a factory for CapabilitySources.
func CapabilitySources(a *app.App) *CapabilitySourceFactory {
	return &CapabilitySourceFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *CapabilitySourceFactory) Count(n int) *CapabilitySourceFactory { f.count = n; return f }

// Definition returns fake attributes for one CapabilitySource. Edit to taste.
func (f *CapabilitySourceFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"capability_id": faker.Words(3),
		"source_id":     faker.Words(3),
		"config":        faker.Words(3),
		"active":        faker.Bool(),
	}
}

// Create builds and persists Count records via the ORM.
func (f *CapabilitySourceFactory) Create(ctx context.Context) ([]db.CapabilitySource, error) {
	out := make([]db.CapabilitySource, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.CapabilitySources(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
