// Code generated by togo. Factory — builds fake Entities via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// EntityFactory builds fake Entity records.
type EntityFactory struct {
	app   *app.App
	count int
}

// Entities starts a factory for Entities.
func Entities(a *app.App) *EntityFactory {
	return &EntityFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *EntityFactory) Count(n int) *EntityFactory { f.count = n; return f }

// Definition returns fake attributes for one Entity. Edit to taste.
func (f *EntityFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"name":         faker.Name(),
		"slug":         faker.Words(3),
		"kind":         faker.Words(3),
		"description":  faker.Paragraph(),
		"logo_url":     "https://" + faker.Word() + ".example.com",
		"website":      faker.Words(3),
		"sector":       faker.Words(3),
		"headquarters": faker.Words(3),
		"founded_year": faker.Int(1, 1000),
		"claimed":      faker.Bool(),
	}
}

// Create builds and persists Count records via the ORM.
func (f *EntityFactory) Create(ctx context.Context) ([]db.Entity, error) {
	out := make([]db.Entity, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Entities(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
