// Code generated by togo. Factory — builds fake Leads via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// LeadFactory builds fake Lead records.
type LeadFactory struct {
	app   *app.App
	count int
}

// Leads starts a factory for Leads.
func Leads(a *app.App) *LeadFactory {
	return &LeadFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *LeadFactory) Count(n int) *LeadFactory { f.count = n; return f }

// Definition returns fake attributes for one Lead. Edit to taste.
func (f *LeadFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"email":        faker.Email(),
		"whatsapp":     faker.Words(3),
		"message":      faker.Words(3),
		"source_type":  faker.Words(3),
		"source_page":  faker.Words(3),
		"source_agent": faker.Words(3),
	}
}

// Create builds and persists Count records via the ORM.
func (f *LeadFactory) Create(ctx context.Context) ([]db.Lead, error) {
	out := make([]db.Lead, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Leads(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
