// Code generated by togo. Factory — builds fake Narratives via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// NarrativeFactory builds fake Narrative records.
type NarrativeFactory struct {
	app   *app.App
	count int
}

// Narratives starts a factory for Narratives.
func Narratives(a *app.App) *NarrativeFactory {
	return &NarrativeFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *NarrativeFactory) Count(n int) *NarrativeFactory { f.count = n; return f }

// Definition returns fake attributes for one Narrative. Edit to taste.
func (f *NarrativeFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"title":             faker.Name(),
		"kind":              faker.Words(3),
		"body_md":           faker.Paragraph(),
		"period_start":      faker.Time(),
		"period_end":        faker.Time(),
		"window_days":       faker.Int(1, 1000),
		"model":             faker.Words(3),
		"prompt_tokens":     faker.Int(1, 1000),
		"completion_tokens": faker.Int(1, 1000),
		"status":            faker.Words(3),
	}
}

// Create builds and persists Count records via the ORM.
func (f *NarrativeFactory) Create(ctx context.Context) ([]db.Narrative, error) {
	out := make([]db.Narrative, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Narratives(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
