// Code generated by togo. Factory — builds fake Prompts via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// PromptFactory builds fake Prompt records.
type PromptFactory struct {
	app   *app.App
	count int
}

// Prompts starts a factory for Prompts.
func Prompts(a *app.App) *PromptFactory {
	return &PromptFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *PromptFactory) Count(n int) *PromptFactory { f.count = n; return f }

// Definition returns fake attributes for one Prompt. Edit to taste.
func (f *PromptFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"capability_id": faker.Words(3),
		"prompt_key":    faker.Words(3),
		"content_en":    faker.Paragraph(),
		"content_ar":    faker.Paragraph(),
		"version":       faker.Int(1, 1000),
		"active":        faker.Bool(),
	}
}

// Create builds and persists Count records via the ORM.
func (f *PromptFactory) Create(ctx context.Context) ([]db.Prompt, error) {
	out := make([]db.Prompt, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Prompts(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
