// Code generated by togo. Factory — builds fake Sources via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// SourceFactory builds fake Source records.
type SourceFactory struct {
	app   *app.App
	count int
}

// Sources starts a factory for Sources.
func Sources(a *app.App) *SourceFactory {
	return &SourceFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *SourceFactory) Count(n int) *SourceFactory { f.count = n; return f }

// Definition returns fake attributes for one Source. Edit to taste.
func (f *SourceFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"slug":    faker.Words(3),
		"name":    faker.Name(),
		"kind":    faker.Words(3),
		"config":  faker.Words(3),
		"enabled": faker.Bool(),
	}
}

// Create builds and persists Count records via the ORM.
func (f *SourceFactory) Create(ctx context.Context) ([]db.Source, error) {
	out := make([]db.Source, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Sources(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
