// Code generated by togo. Next.js page for Articles.
"use client";

import { useArticles } from "@/lib/hooks/useArticles";

export default function ArticlesPage() {
  const { data, isLoading } = useArticles();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Articles</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
