// Code generated by togo. GraphQL resolvers for Agent via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Agent(ctx context.Context, id string) (*db.Agent, error) {
	return models.Agents(r.App).Find(ctx, id)
}

func (r *queryResolver) Agents(ctx context.Context) ([]*db.Agent, error) {
	rows, err := models.Agents(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Agent, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateAgent(ctx context.Context, input graphgen.CreateAgentInput) (*db.Agent, error) {
	row, err := models.Agents(r.App).Create(ctx, map[string]any{
		"name":        input.Name,
		"slug":        input.Slug,
		"module":      input.Module,
		"tagline":     input.Tagline,
		"description": input.Description,
		"image_url":   input.ImageURL,
		"cta_text":    input.CtaText,
		"cta_subtext": input.CtaSubtext,
		"sort_order":  input.SortOrder,
		"active":      input.Active,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "agent.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteAgent(ctx context.Context, id string) (bool, error) {
	if err := models.Agents(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "agent.deleted", id)
	return true, nil
}
