// Code generated by togo. GraphQL resolvers for Alert via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Alert(ctx context.Context, id string) (*db.Alert, error) {
	return models.Alerts(r.App).Find(ctx, id)
}

func (r *queryResolver) Alerts(ctx context.Context) ([]*db.Alert, error) {
	rows, err := models.Alerts(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Alert, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateAlert(ctx context.Context, input graphgen.CreateAlertInput) (*db.Alert, error) {
	row, err := models.Alerts(r.App).Create(ctx, map[string]any{
		"signal":       input.Signal,
		"severity":     input.Severity,
		"title":        input.Title,
		"summary":      input.Summary,
		"article_id":   input.ArticleID,
		"entity_id":    input.EntityID,
		"acknowledged": input.Acknowledged,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "alert.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteAlert(ctx context.Context, id string) (bool, error) {
	if err := models.Alerts(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "alert.deleted", id)
	return true, nil
}
