// Code generated by togo. GraphQL resolvers for Article via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Article(ctx context.Context, id string) (*db.Article, error) {
	return models.Articles(r.App).Find(ctx, id)
}

func (r *queryResolver) Articles(ctx context.Context) ([]*db.Article, error) {
	rows, err := models.Articles(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Article, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateArticle(ctx context.Context, input graphgen.CreateArticleInput) (*db.Article, error) {
	row, err := models.Articles(r.App).Create(ctx, map[string]any{
		"url":               input.URL,
		"title":             input.Title,
		"content":           input.Content,
		"summary":           input.Summary,
		"why_it_matters":    input.WhyItMatters,
		"source_name":       input.SourceName,
		"source_type":       input.SourceType,
		"image_url":         input.ImageURL,
		"published_at":      input.PublishedAt,
		"status":            input.Status,
		"harvester_item_id": input.HarvesterItemID,
		"linked_venture_id": input.LinkedVentureID,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "article.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteArticle(ctx context.Context, id string) (bool, error) {
	if err := models.Articles(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "article.deleted", id)
	return true, nil
}
