// Code generated by togo. GraphQL resolvers for CapabilitySource via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) CapabilitySource(ctx context.Context, id string) (*db.CapabilitySource, error) {
	return models.CapabilitySources(r.App).Find(ctx, id)
}

func (r *queryResolver) CapabilitySources(ctx context.Context) ([]*db.CapabilitySource, error) {
	rows, err := models.CapabilitySources(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.CapabilitySource, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateCapabilitySource(ctx context.Context, input graphgen.CreateCapabilitySourceInput) (*db.CapabilitySource, error) {
	row, err := models.CapabilitySources(r.App).Create(ctx, map[string]any{
		"capability_id": input.CapabilityID,
		"source_id":     input.SourceID,
		"config":        input.Config,
		"active":        input.Active,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "capability_source.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteCapabilitySource(ctx context.Context, id string) (bool, error) {
	if err := models.CapabilitySources(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "capability_source.deleted", id)
	return true, nil
}
