// Code generated by togo. GraphQL resolvers for Capability via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Capability(ctx context.Context, id string) (*db.Capability, error) {
	return models.Capabilities(r.App).Find(ctx, id)
}

func (r *queryResolver) Capabilities(ctx context.Context) ([]*db.Capability, error) {
	rows, err := models.Capabilities(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Capability, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateCapability(ctx context.Context, input graphgen.CreateCapabilityInput) (*db.Capability, error) {
	row, err := models.Capabilities(r.App).Create(ctx, map[string]any{
		"slug":           input.Slug,
		"name_en":        input.NameEn,
		"name_ar":        input.NameAr,
		"kind":           input.Kind,
		"enabled":        input.Enabled,
		"nav_order":      input.NavOrder,
		"nav_icon":       input.NavIcon,
		"route":          input.Route,
		"description_en": input.DescriptionEn,
		"description_ar": input.DescriptionAr,
		"config":         input.Config,
		"workflow_steps": input.WorkflowSteps,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "capability.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteCapability(ctx context.Context, id string) (bool, error) {
	if err := models.Capabilities(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "capability.deleted", id)
	return true, nil
}
