// Code generated by togo. GraphQL resolvers for Entity via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Entity(ctx context.Context, id string) (*db.Entity, error) {
	return models.Entities(r.App).Find(ctx, id)
}

func (r *queryResolver) Entities(ctx context.Context) ([]*db.Entity, error) {
	rows, err := models.Entities(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Entity, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateEntity(ctx context.Context, input graphgen.CreateEntityInput) (*db.Entity, error) {
	row, err := models.Entities(r.App).Create(ctx, map[string]any{
		"name":         input.Name,
		"slug":         input.Slug,
		"kind":         input.Kind,
		"description":  input.Description,
		"logo_url":     input.LogoURL,
		"website":      input.Website,
		"sector":       input.Sector,
		"headquarters": input.Headquarters,
		"founded_year": input.FoundedYear,
		"claimed":      input.Claimed,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "entity.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteEntity(ctx context.Context, id string) (bool, error) {
	if err := models.Entities(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "entity.deleted", id)
	return true, nil
}
