// Code generated by togo. GraphQL resolvers for Lead via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Lead(ctx context.Context, id string) (*db.Lead, error) {
	return models.Leads(r.App).Find(ctx, id)
}

func (r *queryResolver) Leads(ctx context.Context) ([]*db.Lead, error) {
	rows, err := models.Leads(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Lead, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateLead(ctx context.Context, input graphgen.CreateLeadInput) (*db.Lead, error) {
	row, err := models.Leads(r.App).Create(ctx, map[string]any{
		"email":        input.Email,
		"whatsapp":     input.Whatsapp,
		"message":      input.Message,
		"source_type":  input.SourceType,
		"source_page":  input.SourcePage,
		"source_agent": input.SourceAgent,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "lead.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteLead(ctx context.Context, id string) (bool, error) {
	if err := models.Leads(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "lead.deleted", id)
	return true, nil
}
