// Code generated by togo. GraphQL resolvers for Narrative via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Narrative(ctx context.Context, id string) (*db.Narrative, error) {
	return models.Narratives(r.App).Find(ctx, id)
}

func (r *queryResolver) Narratives(ctx context.Context) ([]*db.Narrative, error) {
	rows, err := models.Narratives(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Narrative, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateNarrative(ctx context.Context, input graphgen.CreateNarrativeInput) (*db.Narrative, error) {
	row, err := models.Narratives(r.App).Create(ctx, map[string]any{
		"title":             input.Title,
		"kind":              input.Kind,
		"body_md":           input.BodyMd,
		"period_start":      input.PeriodStart,
		"period_end":        input.PeriodEnd,
		"window_days":       input.WindowDays,
		"model":             input.Model,
		"prompt_tokens":     input.PromptTokens,
		"completion_tokens": input.CompletionTokens,
		"status":            input.Status,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "narrative.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteNarrative(ctx context.Context, id string) (bool, error) {
	if err := models.Narratives(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "narrative.deleted", id)
	return true, nil
}
