// Code generated by togo. GraphQL resolvers for Prompt via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Prompt(ctx context.Context, id string) (*db.Prompt, error) {
	return models.Prompts(r.App).Find(ctx, id)
}

func (r *queryResolver) Prompts(ctx context.Context) ([]*db.Prompt, error) {
	rows, err := models.Prompts(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Prompt, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreatePrompt(ctx context.Context, input graphgen.CreatePromptInput) (*db.Prompt, error) {
	row, err := models.Prompts(r.App).Create(ctx, map[string]any{
		"capability_id": input.CapabilityID,
		"prompt_key":    input.PromptKey,
		"content_en":    input.ContentEn,
		"content_ar":    input.ContentAr,
		"version":       input.Version,
		"active":        input.Active,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "prompt.created", row)
	return row, nil
}

func (r *mutationResolver) DeletePrompt(ctx context.Context, id string) (bool, error) {
	if err := models.Prompts(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "prompt.deleted", id)
	return true, nil
}
