// Code generated by togo. GraphQL resolvers for Source via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/saudi-ventures/saudi-ventures/internal/db/gen"
	graphgen "github.com/saudi-ventures/saudi-ventures/internal/graph/gen"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

func (r *queryResolver) Source(ctx context.Context, id string) (*db.Source, error) {
	return models.Sources(r.App).Find(ctx, id)
}

func (r *queryResolver) Sources(ctx context.Context) ([]*db.Source, error) {
	rows, err := models.Sources(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Source, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreateSource(ctx context.Context, input graphgen.CreateSourceInput) (*db.Source, error) {
	row, err := models.Sources(r.App).Create(ctx, map[string]any{
		"slug":    input.Slug,
		"name":    input.Name,
		"kind":    input.Kind,
		"config":  input.Config,
		"enabled": input.Enabled,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "source.created", row)
	return row, nil
}

func (r *mutationResolver) DeleteSource(ctx context.Context, id string) (bool, error) {
	if err := models.Sources(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "source.deleted", id)
	return true, nil
}
