// Code generated by togo. Next.js page for Narratives.
"use client";

import { useNarratives } from "@/lib/hooks/useNarratives";

export default function NarrativesPage() {
  const { data, isLoading } = useNarratives();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Narratives</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
