-- Code generated by togo. SQLite schema fragment for sqlc and migrate.
CREATE TABLE IF NOT EXISTS agents (
    id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    name text NOT NULL,
    slug text NOT NULL,
    module text NOT NULL,
    tagline text,
    description text,
    image_url text,
    cta_text text NOT NULL,
    cta_subtext text,
    sort_order integer,
    active boolean NOT NULL,
    created_at datetime NOT NULL DEFAULT (datetime('now')),
    updated_at datetime NOT NULL DEFAULT (datetime('now'))
);
