-- Code generated by togo. SQLite schema fragment for sqlc and migrate.
CREATE TABLE IF NOT EXISTS entities (
    id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    name text NOT NULL,
    slug text NOT NULL,
    kind text NOT NULL,
    description text,
    logo_url text,
    website text,
    sector text,
    headquarters text,
    founded_year integer,
    claimed boolean NOT NULL,
    created_at datetime NOT NULL DEFAULT (datetime('now')),
    updated_at datetime NOT NULL DEFAULT (datetime('now'))
);
