-- Code generated by togo. SQLite schema fragment for sqlc and migrate.
CREATE TABLE IF NOT EXISTS leads (
    id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    email text NOT NULL,
    whatsapp text NOT NULL,
    message text,
    source_type text NOT NULL,
    source_page text NOT NULL,
    source_agent text,
    created_at datetime NOT NULL DEFAULT (datetime('now')),
    updated_at datetime NOT NULL DEFAULT (datetime('now'))
);
