// Code generated by togo (seeder) — uses the factory; adjust the count freely.
package seeders

import (
	"context"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/factories"
)

// SeedAgent inserts fake Agents via the factory.
func SeedAgent(ctx context.Context, a *app.App) error {
	_, err := factories.Agents(a).Count(5).Create(ctx)
	return err
}
