package seeders

import (
	"context"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/models"
)

// SeedCapability loads the v0.1 module personas as registry rows (idempotent).
// Each is a pluggable capability — enabled/configured from data, Sentra-style —
// that drives a public section and its contextual lead CTA.
func SeedCapability(ctx context.Context, a *app.App) error {
	if _, err := a.SQLDB.ExecContext(ctx, "DELETE FROM capabilities"); err != nil {
		return err
	}
	caps := []map[string]any{
		{"slug": "news-radar", "name_en": "News Radar", "name_ar": "رادار الأخبار", "kind": "capability", "enabled": true, "nav_order": int64(1), "nav_icon": "radar", "route": "/modules/news-radar", "description_en": "Tracks and surfaces the latest Saudi venture-ecosystem news.", "description_ar": "يرصد آخر أخبار منظومة ريادة الأعمال السعودية.", "config": `{"queries":["Saudi startup","Saudi fintech","Saudi venture capital","Riyadh startup","Saudi funding round","Saudi Arabia investment","Saudi tech company","Saudi e-commerce"],"per_query_limit":6}`, "workflow_steps": "[]"},
		{"slug": "startups", "name_en": "List of Startups", "name_ar": "قائمة الشركات الناشئة", "kind": "capability", "enabled": true, "nav_order": int64(2), "nav_icon": "rocket", "route": "/entities", "description_en": "Maintains the directory of Saudi startups and ecosystem entities.", "description_ar": "يحافظ على دليل الشركات الناشئة وكيانات المنظومة في السعودية.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "investment", "name_en": "Investment", "name_ar": "الاستثمار", "kind": "capability", "enabled": true, "nav_order": int64(3), "nav_icon": "trending-up", "route": "/modules/investment", "description_en": "Maps investors, funds, and capital active in the Kingdom.", "description_ar": "يرسم خريطة المستثمرين والصناديق ورؤوس الأموال النشطة في المملكة.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "funding", "name_en": "Funding & Deals", "name_ar": "التمويل والصفقات", "kind": "capability", "enabled": true, "nav_order": int64(4), "nav_icon": "handshake", "route": "/modules/funding", "description_en": "Follows funding rounds, deals, and exits across the ecosystem.", "description_ar": "يتابع جولات التمويل والصفقات وعمليات الخروج في المنظومة.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "sectors", "name_en": "Sectors & Market", "name_ar": "القطاعات والسوق", "kind": "capability", "enabled": true, "nav_order": int64(5), "nav_icon": "layers", "route": "/modules/sectors", "description_en": "Analyzes sector activity and market trends in the Saudi market.", "description_ar": "يحلل نشاط القطاعات واتجاهات السوق في السوق السعودي.", "config": "{}", "workflow_steps": "[]"},

		// Full Sentra-style capability catalog (data-driven; enable/configure per venture).
		{"slug": "projects", "name_en": "Projects", "name_ar": "ملفات القضايا", "kind": "capability", "enabled": true, "nav_order": int64(6), "nav_icon": "folder", "route": "/modules/projects", "description_en": "Organizes analyst work into projects with milestones, assignments, and status tracking.", "description_ar": "ينظم عمل المحللين في مشاريع مع معالم وتعيينات وتتبع الحالة.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "briefing", "name_en": "Briefing", "name_ar": "الإحاطة", "kind": "capability", "enabled": true, "nav_order": int64(7), "nav_icon": "file-text", "route": "/modules/briefing", "description_en": "Generates daily executive intelligence briefings via AI models.", "description_ar": "ينشئ إحاطات استخباراتية تنفيذية يومية عبر نماذج الذكاء الاصطناعي.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "breaking-news", "name_en": "Breaking News", "name_ar": "الأخبار العاجلة", "kind": "capability", "enabled": true, "nav_order": int64(8), "nav_icon": "zap", "route": "/modules/breaking-news", "description_en": "Monitors and surfaces breaking news in real time.", "description_ar": "يرصد ويظهر الأخبار المتسارعة في الوقت الفعلي.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "alert", "name_en": "Alert", "name_ar": "تنبيه", "kind": "capability", "enabled": true, "nav_order": int64(9), "nav_icon": "bell", "route": "/alerts", "description_en": "Alert rules engine with webhook notification delivery.", "description_ar": "محرك قواعد التنبيه مع نشر الإشعارات عبر Webhook.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "coverage", "name_en": "Coverage", "name_ar": "التغطية", "kind": "capability", "enabled": true, "nav_order": int64(10), "nav_icon": "bar-chart", "route": "/modules/coverage", "description_en": "Measures media and platform coverage by scope, source, and topic.", "description_ar": "يقيس تغطية الإعلام والمنصة حسب النطاق والمصدر والموضوع.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "copilot", "name_en": "Copilot", "name_ar": "المساعد", "kind": "capability", "enabled": true, "nav_order": int64(11), "nav_icon": "bot", "route": "/modules/copilot", "description_en": "Interactive AI copilot backed by the smart-assist service and analyst-configurable tools.", "description_ar": "قدرة محادثة ذكاء اصطناعي تفاعلية مدعومة بخدمة المساعد الذكي وأدوات قابلة للإعداد من قبل المحللين.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "compare", "name_en": "Compare", "name_ar": "المقارنة", "kind": "capability", "enabled": true, "nav_order": int64(12), "nav_icon": "git-compare", "route": "/modules/compare", "description_en": "Compares topics with cache management, bilingual topic fetch, and AI-composed agents.", "description_ar": "قدرة مقارنة الموضوعات توفر إدارة ذاكرة التخزين المؤقت وجلب الموضوعات بلغتين وتوليف العوامل بواسطة الذكاء الاصطناعي.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "chat", "name_en": "Chat", "name_ar": "المحادثة", "kind": "capability", "enabled": true, "nav_order": int64(13), "nav_icon": "message-circle", "route": "/modules/chat", "description_en": "Conversational intelligence interface for instant analyst Q&A and guided workflows.", "description_ar": "واجهة استخبارات محادثة لأسئلة وأجوبة المحللين الفورية وسير العمل الموجّه.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "knowledge", "name_en": "Knowledge", "name_ar": "المعرفة", "kind": "capability", "enabled": true, "nav_order": int64(14), "nav_icon": "database", "route": "/modules/knowledge", "description_en": "Maintains an organized knowledge base linking entities, facts, and source documents.", "description_ar": "يحتفظ بقاعدة معرفة منظمة تربط الجهات والحقائق والوثائق المصدرية.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "for-you", "name_en": "For You", "name_ar": "مخصص لك", "kind": "capability", "enabled": true, "nav_order": int64(15), "nav_icon": "user", "route": "/modules/for-you", "description_en": "Personalized intelligence digest — narratives, alerts, and entities matched to your scope and followed topics.", "description_ar": "خلاصة استخباراتية مخصصة — سرديات وتنبيهات وجهات تتطابق مع نطاقك والموضوعات التي تتابعها.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "event", "name_en": "Event", "name_ar": "حدث", "kind": "capability", "enabled": true, "nav_order": int64(16), "nav_icon": "calendar", "route": "/modules/event", "description_en": "Tracks and classifies diplomatic, political, and strategic events.", "description_ar": "يرصد الأحداث الدبلوماسية والسياسية والاستراتيجية ويصنّفها.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "entity", "name_en": "Entity", "name_ar": "كيان", "kind": "capability", "enabled": true, "nav_order": int64(17), "nav_icon": "tag", "route": "/entities", "description_en": "Tracks extracted entities — people, organizations, and locations — across all data sources.", "description_ar": "يتابع الجهات المُستقاة — أشخاص ومنظمات ومواقع — عبر جميع مصادر البيانات.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "search", "name_en": "Search", "name_ar": "البحث", "kind": "capability", "enabled": true, "nav_order": int64(18), "nav_icon": "search", "route": "/modules/search", "description_en": "Full-text search across all intelligence inputs (alerts, events, narratives, tasks, coverage, entities) using BM25 ranking.", "description_ar": "بحث نصي كامل عبر جميع مدخلات الاستخبارات (تنبيهات، أحداث، روايات، مهام، تغطيات، كيانات) باستخدام ترتيب BM25.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "personas", "name_en": "Personas", "name_ar": "الشخصيات", "kind": "capability", "enabled": true, "nav_order": int64(19), "nav_icon": "users", "route": "/modules/personas", "description_en": "Builds and manages analyst-defined personas for narrative attribution and actor classification.", "description_ar": "يبني الشخصيات المُعرّفة من المحللين ويديرها لنسب السرديات وتصنيف الجهات الفاعلة.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "notification", "name_en": "Notification", "name_ar": "إشعار", "kind": "capability", "enabled": true, "nav_order": int64(20), "nav_icon": "bell", "route": "/modules/notification", "description_en": "Delivers real-time notifications based on configurable alert rules.", "description_ar": "يوصل الإشعارات الفورية بناءً على قواعد تنبيه قابلة للإعداد.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "narrative", "name_en": "Narrative", "name_ar": "سردية", "kind": "capability", "enabled": true, "nav_order": int64(21), "nav_icon": "book-open", "route": "/narratives", "description_en": "Assembles related signals into coherent narratives and tracks their evolution.", "description_ar": "يجمع الإشارات ذات الصلة في سرديات متماسكة ويتابع تطورها.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "war-room", "name_en": "War Room", "name_ar": "غرفة الحرب", "kind": "capability", "enabled": true, "nav_order": int64(22), "nav_icon": "shield", "route": "/modules/war-room", "description_en": "High-alert operational mode with crisis dashboards for critical situations.", "description_ar": "وضع تشغيلي للتنبيهات المرتفعة ولوحات الأزمات يُفعّله المسؤولون في الحالات الحرجة.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "trend-detection", "name_en": "Trend Detection", "name_ar": "شائع", "kind": "capability", "enabled": true, "nav_order": int64(23), "nav_icon": "trending-up", "route": "/modules/trend-detection", "description_en": "Detects emerging trends and momentum shifts across monitored scopes and time windows.", "description_ar": "يرصد الاتجاهات الناشئة وتحولات سرعة المواضيع عبر النطاقات والنوافذ الزمنية المراقبة.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "dashboard", "name_en": "Dashboard", "name_ar": "تركيز اليوم", "kind": "capability", "enabled": true, "nav_order": int64(24), "nav_icon": "layout-grid", "route": "/modules/dashboard", "description_en": "Provides an overview of intelligence activity, key metrics, and priority signals across monitored scopes.", "description_ar": "يوفر نظرة عامة على نشاط الاستخبارات والمقاييس الرئيسية وإشارات الأولوية عبر جميع النطاقات المراقبة.", "config": "{}", "workflow_steps": "[]"},
		{"slug": "task", "name_en": "Task", "name_ar": "المهام", "kind": "capability", "enabled": true, "nav_order": int64(25), "nav_icon": "check-square", "route": "/modules/task", "description_en": "Creates actionable tasks from intelligence signals for analyst follow-up.", "description_ar": "ينشئ مهام قابلة للتنفيذ من إشارات الاستخبارات لمتابعة المحللين.", "config": "{}", "workflow_steps": "[]"},
	}
	for _, c := range caps {
		if _, err := models.Capabilities(a).Create(ctx, c); err != nil {
			return err
		}
	}
	return nil
}
