// Code generated by togo (seeder) — uses the factory; adjust the count freely.
package seeders

import (
	"context"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/factories"
)

// SeedCapabilitySource inserts fake CapabilitySources via the factory.
func SeedCapabilitySource(ctx context.Context, a *app.App) error {
	_, err := factories.CapabilitySources(a).Count(5).Create(ctx)
	return err
}
