package seeders

import (
	"context"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
)

// SeedNarrative is intentionally a no-op: narratives are generated by the
// intelligence pipeline, not fabricated. Kept so the seeder registry compiles.
func SeedNarrative(ctx context.Context, a *app.App) error {
	_ = ctx
	_ = a
	return nil
}
