// Code generated by togo. DO NOT EDIT.
package seeders

import (
	"context"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
)

// SeedAll runs every resource seeder. Regenerated from togo.resources.yaml.
func SeedAll(ctx context.Context, a *app.App) error {
	if err := SeedAgent(ctx, a); err != nil {
		return err
	}
	if err := SeedEntity(ctx, a); err != nil {
		return err
	}
	if err := SeedLead(ctx, a); err != nil {
		return err
	}
	return nil
}
