// Code generated by togo (seeder) — uses the factory; adjust the count freely.
package seeders

import (
	"context"

	"github.com/saudi-ventures/saudi-ventures/internal/app"
	"github.com/saudi-ventures/saudi-ventures/internal/factories"
)

// SeedSource inserts fake Sources via the factory.
func SeedSource(ctx context.Context, a *app.App) error {
	_, err := factories.Sources(a).Count(5).Create(ctx)
	return err
}
