// Code generated by togo. Next.js page for Prompts.
"use client";

import { usePrompts } from "@/lib/hooks/usePrompts";

export default function PromptsPage() {
  const { data, isLoading } = usePrompts();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Prompts</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
